### ISSUE TITLE
Which kmers are used?

### ISSUE THREAD

**Issue by ctseto** [GATB/simka#7]
Can the kmers corresponding to a partition be recovered?

**Comment by rchikhi** [comment]
Hi Charlie, I believe the question would need to be a bit more detailed..

**Comment by ctseto** [comment]
Mean culpa. I'm interested in analysis of metagenomes for sample discrimination. I run simka on a set of assemblies and am curious about what the kmer partitioning process entailed, and how sample kmers were assigned to the partitions/bins.

**Comment by clemaitre** [comment]
Hi Charlie,

The kmer partitioning is not used to discriminate the samples but to make the kmer counting step faster. Kmers are distributed to P different files according to a given hash function, and then the kmers of each file can be counted independently and more rapidly. The distribution of kmers (given by the hash function) has no biological or statistical meaning and is just a trick to divide the problem and count the kmers faster. Therefore, I do not think that recovering kmers of each partition will answer your question.

However, Simka is the good tool if you want to cluster or discriminate your samples. It computes  distances between all pairs of samples based on the kmer counts, and you can surely cluster samples based on these distances. Simka was actually developped for this objective. In fact, in the `scripts/visualization` directory, you will find python and R scripts to perform PCA and sample classification based on the distance matrices output by simka. Note that you can also run simka directly on your raw fastq datasets (instead of assemblies).

If you still need to recover kmer sequences, for instance recovering subsets of kmers according to their presence/absence in some datasets, you may have a look at the software DSK : http://github.com/GATB/dsk and its option `-solidity-custom`.

**Comment by ctseto** [comment]
The ecological distance clusterings were quite insightful. That said, not sure I follow along in re DSK documentation. 

I presume it is dsk -file contigs1.fa,contigs2.fa -solidity-kind custom -solidity-custom , though I'm not quite sure what the -solidity-custom option is specifying for. Is it a file with a list of kmers ("specifies list of files where kmer must be present"). I generally get  "Kmer solidity custom has different number of values  (11) than banks (2)"; where banks appears to correspond to the number of files appended to flag -file.

**Comment by ctseto** [comment]
Dr. Lemaitre,
Thanks for your help! Have some supplemental questions in re DSK, which I'll instead ask at the dsk repo.
~Charlie
